### ISSUE TITLE
Easy Lints to implement

### ISSUE THREAD

**Issue by Luro02** [Feuermagier/autograder#18]
- [x] Tri-states like `Option<bool>` or nullable `Boolean` should be avoided
- [x] Optional should never be an argument, because of nullability resulting in tri-state
- [ ] #135
- [x] Shadowing of variables should be avoided
- [ ] #136
- [x] Labels on Loops should be avoided in general, because it makes control flow harder to read (https://stackoverflow.com/questions/33689466/labels-in-java-bad-practice/33689582#33689582)
- [x] Unnecessary use of boxed types, where the primitive type would work as well. They make only sense, when they are nullable or used in generics
- [ ] #134
```java
String a;
// ... some code

// then initialized when it is used:
a = "abc";
```
- [x] abstract/super classes that only have methods should be interfaces, covered by #51
- [x] regex patterns without a comment explaining what it does
- [x] Arguments should not be final
Why?
- harder to read
- introduces extra noise
- reassignment of arguments is almost never done and should not be dne

**Comment by Feuermagier** [comment]
A few notes:
* I think generic parameters should be covered by checkstyle
* Boxed primitives are sometimes detected by the [complexity.WrapperInstantiationCheck](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/complexity/WrapperInstantiationCheck.java)
* I gues we need a way to build CFGs to detec cases where locals are unitialized because they are initialized in e.g. ifs
* I think we should in some way assess the complexity of regex patterns, because really simple patterns (e.g. \d+) can be fine without a comment
* I agree with you regarding final arguments, but judging from past correcting sessions of the final tasks I know that some folks have different opinions

**Comment by Luro02** [comment]
Not everything has to subtract points. It is better to emit a custom comment for some things, so there should be no problem with marking final arguments as redundant

**Comment by Luro02** [comment]
> Boxed primitives are sometimes detected by the [complexity.WrapperInstantiationCheck](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/complexity/WrapperInstantiationCheck.java)

It is not able to detect them in arrays: `Character[] charArray = {'a', 'b', 'c'}`
