### ISSUE TITLE
Deployment to Maven Central

### ISSUE THREAD

**Issue by dfuchss** [Feuermagier/autograder#2]
Could you deploy the artifacts to Maven Central? Then we could easily integrate them.

**Comment by Feuermagier** [comment]
Could we use Jitpack instead of Maven Central? Maybe it would also be a good idea to move the Autograder to the SDQ organization so that you aren't dependend on my personal Github account :). 

Also, I kind of like the current separate jar file, because the checks still change all the time and it is easier for other tutors to only download a new jar file when something changed, instead of making a new release of the Grading Tool and requiring all tutors to download it.

**Comment by dfuchss** [comment]
Jitpack alters the groupId which could cause problems (that's why we moved projects from jitpack to Maven Central. The option to exchange the jar is interesting. Nevertheless, for the eclipse bundle I would prefer to include it as dependency. (With the option to load a newer jar, if you want this option :) )

**Comment by Feuermagier** [comment]
Okay, I'll have a look into how Maven Central works

**Comment by Feuermagier** [comment]
@dfuchss Ok, so I've deployed autograder-core to Maven central (group id de.firemage.autograder), but when adding the package to the Eclipse target platform and importing classes I get many OSGi constraint violations. Do you have any idea how to fix this?

**Comment by dfuchss** [comment]
Could you push your changes to a branch? Then I'll take a look at it.
