### ISSUE TITLE
German Comment not recognized

### ISSUE THREAD

**Issue by CDaut** [Feuermagier/autograder#280]
### Summary

Does not flag the following comment as german although all other Comments are in English

### Reproducer

```java
stringBuilder.append(done ? TOGGLED_TASK : NOT_TOGGLED_TASK); // Zustand
```

**Comment by Luro02** [comment]
The lint has not been enabled, because it has too many false-positives for later submissions (where it is rare to see comments in mixed language). A single word is not enough for the language detection libraries to decide which language the input is written in (especially because some words are shared between different languages).
