### ISSUE TITLE
Wrong penalty for final attributes that should be static constants

### ISSUE THREAD

**Issue by Fenmore** [Feuermagier/autograder#75]
If an attribute is final and non-static and thus written in camel case but initialized in a constant way like `private final int myNumber = 2;` the penaly for bad naming ("Schlechter Bezeichner") is applied while the actual mistake is this attribute being non-static and therefore Instance Attribute penalty ("Instanzattribut") would be more appropiate.

**Comment by Luro02** [comment]
Are you sure that only one penalty has been applied? I have to check which of the two lints triggers the penalty. There is one for constants [`ConstantsHaveDescriptiveNamesCheck`](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/naming/ConstantsHaveDescriptiveNamesCheck.java) and one for variables [`VariablesHaveDescriptiveNamesCheck`](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/naming/VariablesHaveDescriptiveNamesCheck.java).

Either way, I do think that this is a bad name.

**Comment by Feuermagier** [comment]
I'm pretty sure the reason is the [ConstantNamingAndQualifierCheck](https://github.com/Feuermagier/autograder/blob/main/autograder-core/src/main/java/de/firemage/autograder/core/check/general/ConstantNamingAndQualifierCheck.java) that adds a CONSTANT_NOT_STATIC_OR_NOT_UPPER_CAMEL_CASE problem which is mapped to the identifierNaming penalty by the grading tool.

**Comment by Luro02** [comment]
I think I have fixed this, will look into the mapping now
